FROM golang:1.23-alpine AS build
WORKDIR /app
RUN apk add --no-cache git \
 	&& go install github.com/pressly/goose/v3/cmd/goose@v3.21.1

FROM alpine:3.20
RUN adduser -D -u 10001 nonroot
USER nonroot
WORKDIR /work
COPY --from=build /go/bin/goose /usr/local/bin/goose
ENTRYPOINT ["goose"]

