services:
  postgres:
    image: postgres:16-alpine
    container_name: kart-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kart
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kart"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    image: kart-migrate:local
    container_name: kart-migrate
    volumes:
      - ./db/migrations:/migrations:ro
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://postgres:postgres@postgres:5432/kart?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["goose", "-dir", "/migrations", "up"]

  app:
    build: .
    image: kart:local
    container_name: kart-app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/kart?sslmode=disable
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"

volumes:
  pgdata:


