// Code generated by mockery v2.53.5. DO NOT EDIT.

package repomock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlc "kart/internal/sqlc"
)

// CouponRepository is an autogenerated mock type for the CouponRepository type
type CouponRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, code
func (_m *CouponRepository) Get(ctx context.Context, code string) (sqlc.Coupon, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 sqlc.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlc.Coupon, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlc.Coupon); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(sqlc.Coupon)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCouponRepository creates a new instance of CouponRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCouponRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CouponRepository {
	mock := &CouponRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
