// Code generated by mockery v2.53.5. DO NOT EDIT.

package repomock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlc "kart/internal/sqlc"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// CreateWithItems provides a mock function with given fields: ctx, o, items
func (_m *OrderRepository) CreateWithItems(ctx context.Context, o sqlc.Order, items []sqlc.OrderItem) (string, error) {
	ret := _m.Called(ctx, o, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithItems")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.Order, []sqlc.OrderItem) (string, error)); ok {
		return rf(ctx, o, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.Order, []sqlc.OrderItem) string); ok {
		r0 = rf(ctx, o, items)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.Order, []sqlc.OrderItem) error); ok {
		r1 = rf(ctx, o, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
