// Code generated by mockery v2.53.5. DO NOT EDIT.

package servermock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "kart/internal/service"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// PlaceOrder provides a mock function with given fields: ctx, in
func (_m *OrderService) PlaceOrder(ctx context.Context, in service.PlaceOrderInput) (service.PlaceOrderResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 service.PlaceOrderResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PlaceOrderInput) (service.PlaceOrderResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PlaceOrderInput) service.PlaceOrderResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(service.PlaceOrderResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PlaceOrderInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
