// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetCoupon(ctx context.Context, code string) (Coupon, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	GetProductsByIDs(ctx context.Context, dollar_1 []string) ([]Product, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error
	InsertOrderItems(ctx context.Context, arg InsertOrderItemsParams) error
	ListAllProducts(ctx context.Context) ([]Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	TryRedeemSingleUse(ctx context.Context, code string) (string, error)
}

var _ Querier = (*Queries)(nil)
